---
layout: doc
title: Troubleshooting CleanSpeak
description: Troubleshoot any issues that might arise while install or running CleanSpeak or contact Inversoft Support for assistance.
---

== Overview

If any problems arise or if you are unable to access CleanSpeak, consult the CleanSpeak log files. In most cases API errors will be written out to the cleanspeak-webservice.log file. Errors that you encounter in the management interface will be found in the `cleanspeak-management-interface.log`.

Please email support@inversoft.com if you need assistance. If possible, when contacting Inversoft support, zip the contents of the logs directory and attach it to the email.

=== Logs

The following are the default locations for each of the CleanSpeak log files. You may or may not have all of the CleanSpeak services installed on the same system so you may not have all of the following logs on your server.

[source,shell]
.Linux and Mac OS X
----
/usr/local/inversoft/logs/cleanspeak-management-interface.log
/usr/local/inversoft/logs/cleanspeak-webservice.log
/usr/local/inversoft/logs/cleanspeak-search-engine.log
----

These paths assume the suggested product location of `C:\inversoft`. This path may be different on your system depending on where you unpacked the zip files.
[source,shell]
.Windows
----
C:\inversoft\logs\cleanspeak-management-interface.log
C:\inversoft\logs\cleanspeak-webservice.log
C:\inversoft\logs\cleanspeak-search-engine.log
----

=== Database Connections

If you find that CleanSpeak is unable to connect to the database, ensure you are able to use a command line client connection to successfully make a connection using the same port and credentials.

Some MySQL services such as Microsoft Azure may require a specific version of TLS to connect successfully. At the time of writing this note, the MySQL connector will not attempt to utilize TLSv1.2 by default, so when connecting to a service that requires this version you will need to explicitly request this version of TLS on the connection string. For example, appending this `enabledTLSProtocols=TLSv1.2` to the connection string will allow you to successfully connect to an Azure managed MySQL database. See https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-using-ssl.html[MySQL Connector : Connecting Securely UsingSSL] for additional information.
