---
layout: doc
title: Search Engine Installation
description: Install the CleanSpeak Search Engine bundle for full text searching and other CleanSpeak features
---

== Download the Packages

This guide will assist you with installing a CleanSpeak Search Engine on your server (Linux, macOS, or Windows) and works equally well for development environments. These instructions are only for deployments that need CleanSpeak Search Engine to run on a separate server or need CleanSpeak Search Engine to be scaled horizontally.

In most circumstances, you will not need to install CleanSpeak Search Engine on a separate server and can skip this section.

Log into the CleanSpeak website at https://account.cleanspeak.com/account/, navigate to the Licenses section, and click on Download CleanSpeak. You will need to download one of the CleanSpeak Search Engine package that matches the operating system you will be installing CleanSpeak on.

== Red Hat

Use the RPM bundle to install on a Red Hat system (including Fedora and CentOS). Execute this command to install the CleanSpeak Search Engine RPM (replace with the correct <version> number):

[source,shell]
----
$ sudo rpm -i cleanspeak-search-engine-<version>.rpm
----

== Debian

Use the DEB bundle to install on a Debian system (including Ubuntu, Mint, and Debian base). Execute this command to install the CleanSpeak Search Engine DEB (replace with the correct <version> number):

[source,shell]
----
$ sudo dpkg -i cleanspeak-search-engine-<version>.deb
----

== macOS

To install on macOS, use the ZIP bundle. Extract the CleanSpeak Search Engine ZIP file anywhere on the file system. Remember where you extract the file. This location will be referred to as `CLEANSPEAK_HOME`. We suggest extracting this file to a directory like `/usr/local/cleanspeak`.

[NOTE]
====
You can install CleanSpeak in any directory including your home directory. This is a good choice for development machines or when you don't have or want to use sudo to install CleanSpeak.
====

Once the ZIP bundle has been extracted, the directory structure should look similar. If you installed somewhere other than the default `CLEANSPEAK_HOME`, your directory structure would be different. This is only shown as an example.

[source,shell]
----
/usr/local/cleanspeak/config
/usr/local/cleanspeak/config/keystore
/usr/local/cleanspeak/config/cleanspeak.properties
/usr/local/cleanspeak/cleanspeak-search-engine
----

== Windows

To install on Windows use the ZIP bundle. Extract the CleanSpeak Search Engine ZIP file anywhere on the file system. Remember where you extract the file. This location will be referred to as `CLEANSPEAK_HOME`. We suggest extracting this file to a directory such as `C:\cleanspeak` on Windows.

Once the ZIP bundle has been extracted, the directory structure should look similar to this. If you installed somewhere other the default `CLEANSPEAK_HOME`, your directory structure will be different, this is only for shown as an example.

[source,shell]
----
C:\cleanspeak\config
C:\cleanspeak\config\keystore
C:\cleanspeak\config\cleanspeak.properties
C:\cleanspeak\cleanspeak-search-engine\
----

Next, install the Windows service by changing to the directory you installed CleanSpeak (i.e. C:\cleanspeak\cleanspeak-search-engine\elasticsearch\bin) and then running the install command. Here are those two steps:

[source,shell]
----
C:\>cd C:\cleanspeak\cleanspeak-search-engine\elasticsearch\bin
C:\cleanspeak\cleanspeak-search-engine\elasticsearch\bin>CleanSpeakSearchEngine.exe /install
----

== Service Name

As long as your installation method installed CleanSpeak Search Engine as a service, the service name will be as follows:

[cols="4h,6m"]
|===
|Service Name
|cleanspeak-search-engine
|===

You can use the operating system commands to start, stop and check the status of CleanSpeak using this service name.

== Configure Other Servers

Next, you need to configure all of the servers that are running CleanSpeak Management Interface to point them at your CleanSpeak Search Engine servers. For each of these servers, you will need to edit the `cleanspeak.properties` configuration file. More information about this configuration file is located in the link:../reference/configuration[Configuration Reference] section.

When you have this file open for editing, you need to modify two lines like this:

[source,ini]
.cleanspeak.properties
----
cleanspeak-search-engine.embedded=false
cleanspeak-search-engine.servers=<search-engine-server>:8020
----

The first line tells CleanSpeak Management Interface not to use the embedded search engine. The second line tells CleanSpeak Management Interface where to locate the CleanSpeak Search Engine instances. This is a comma separated list of servers and ports. You can use IP addresses or DNS names here. If you are running multiple CleanSpeak Search Engines, you will need to list each one here. You also need to update the configuration on all of the servers running the CleanSpeak Search Engine so that they can find each other.

== Start CleanSpeak Search Engine

CleanSpeak Search Engine should now be ready to run. Use the instructions below to start CleanSpeak Search Engine based on the platform you installed it on. Also note that the `CLEANSPEAK_HOME` directory is the location you installed CleanSpeak Search Engine to.

[source,shell]
.Linux (RPM or DEB package)
----
$ sudo service cleanspeak-search-engine start
----

[source,shell]
.macOS (ZIP package)
----
$ <CLEANSPEAK_HOME>/cleanspeak-search-engine/elasticsearch/bin/elasticsearch -d
----

[source,shell]
.Windows (ZIP package)
----
C:\cleanspeak\cleanspeak-search-engine\elasticsearch\bin>elasticsearch.bat
----

[source,shell]
.Windows Service
----
C:\> net start CleanSpeakSearchEngine
----
