---
layout: doc
title: CleanSpeak Major Version Upgrade (3.x to 4.x)
description: Learn how to upgrade and patch CleanSpeak using our bundles and migration scripts
---

== CleanSpeak Major Version Upgrade (3.x to 4.x)

To download or check on the latest updates, please visit your https://account.cleanspeak.com/account/[CleanSpeak Account] and find the Download link for your license.

[WARNING]
====
If you are upgrading to CleanSpeak version 4.x from 1.x or 2.x, reference link:2.x-3.x[2.x to 3.x] for details on getting to 3.x first.
====

=== Linux

Updating your application is easy if you installed using the RPM or Debian packages. All you need to do is to issue an update command to the dpkg or rpm program and specify the new package file. Here is an example:

[source,shell]
.Red Hat
----
$ sudo rpm -U cleanspeak-search-engine-<version>.rpm
$ sudo rpm -U cleanspeak-webservice-<version>.rpm
$ sudo rpm -U cleanspeak-management-interface-<version>.rpm
----

[source,shell]
.Debian
----
$ sudo dpkg -i cleanspeak-search-engine-<version>.deb
$ sudo dpkg -i cleanspeak-webservice-<version>.deb
$ sudo dpkg -i cleanspeak-management-interface-<version>.deb
----

[NOTE]
====
Running the update script will shut down the CleanSpeak service if it is running. The service will need to be restarted after the update is finished.
====

=== Windows

On Windows, the steps required are different. Follow these steps to upgrade your version on Windows:

1. Download the webapp only bundle
2. Shut-down your Tomcat or your JEE server
3. Rename the CLEANSPEAK_HOME/web directory to something meaningful like web-2009-06-07 (this is helpful in case you need to revert to this version of the application)
4. Extract the update bundle to the CLEANSPEAK_HOME directory. This will place a new directory called web in the directory
5. Restart Tomcat

=== Database

[NOTE]
====
In most cases, you will not need to upgrade you database manually using the information below. CleanSpeak ships with a system called Maintenance Mode. When you restart CleanSpeak after installing a new bundle using the steps above, CleanSpeak will automatically upgrade your database.

You should always backup your database prior to using Maintenance Mode.
====

Depending on your current version and the new version you will be updating to you might need to execute one or more SQL scripts to update your database. These scripts are located in the migrations folder inside the Database Schema ZIP file. This file can be downloaded by logging into your https://account.cleanspeak.com/account/[CleanSpeak Account] and find the Download link for your license, there you will find a package under Database Downloads.

[WARNING]
====
When upgrading your database from a previous version, be sure to only run the scripts located in the migrations folder, the base files mysql.sql and postgresql.sql should only be used during a clean installation when no database schema is present.
====

Inside of the database schema zip file, you will find the following CleanSpeak 3.x migrations, run in this order, starting with the first migration that is
greater than the version you are coming from, and ending with the version that is less than or equal to the target version.

[source]
----
cleanspeak-database-schema
  |
  migrations
    |
    mysql | postgresql
      |
      |- 3.0.5.sql
      |- 3.0.10.sql
      |- 3.1.0.sql
      |- 3.1.3.sql
      |- 3.2.0.sql
      |- 3.3.0.sql
      |- 3.3.2.sql
      |- 3.4.0-RC.1.sql
      |- 3.4.0-RC.2.sql
      |- 3.4.0-RC.3.sql
      |- 3.4.4.sql
      |- 3.4.6.sql
      |- 3.5.1.sql
      |- 3.6.0.sql
      |- 3.7.0.sql
      |- 3.9.0.sql
      |- 3.9.2.sql
      |- 3.12.0.sql
      |- 3.13.0.sql
      |- 3.13.2.sql
      |- 3.14.0.sql
      |- 3.14.1.sql
      |- 3.15.0.sql
      |- 3.16.0.sql
      |- 3.17.0.sql
      |- 3.17.2.sql
      |- 3.18.0.sql
      |- 3.20.0.sql
      |- 3.23.0.sql
      |- 3.23.1.sql
      |- 3.24.0.sql
      |- 3.24.5.sql
      |- 3.25.0.sql
      |- 3.26.0.sql
      |- 3.27.0.sql
      |- 3.28.0.sql
      |- 3.30.0.sql
      |- 3.32.0.sql
      |- 4.0.0.sql
----
