---
layout: doc
title: URL Filter Configuration
description: Learn how to control the quality scores TLDs found by the URL Filter
---

== URL Filter Domain Quality Scores

[WARNING]
====
The `domains.properties` was removed in `3.25.0` in favor of the link:/docs/3.x/tech/apis/url[TLD API]

The quality scores are still relevant but are now accessible/modifiable via the API.
====

CleanSpeak ships with a configuration file that defines the recognized top level domains (TLDs) to be utilized when identifying a string as a URL.

Lists of Top Level Domains

* ICANN http://data.iana.org/TLD/tlds-alpha-by-domain.txt
* Wikipedia http://en.wikipedia.org/wiki/List_of_Internet_top-level_domains

The list of TLDs recognized by ICANN and other Internet standards bodies changes over time. If you have a requirement to recognize URLs when filtering content using a TLD not in the provided configuration follow these steps to extract the configuration file and modify it to add your additional TLD.

[NOTE]
====
*Be Careful*

When modifying this configuration, please take caution. Many of the newly supported TLDs from ICANN are considered dictionary words, such as `.club` and `.ninja`. If you were to add these TLDs to the configuration file by adding them to the [underline]#common# or [underline]#distinguishable# properties the URL filter will not behave as intended. Be sure to add dictionary [underline]#words# to the words property.
====

*Instructions to manually modify the Top Level Domain Configuration*

_Select your platform and follow the instructions. These steps assume the default installation locations for Mac OS X and Windows and that you have the Java Development KIT (JDK) in your PATH. If you do not have the JDK installed you can utilize a zip utility to extract the domains.properties and copy into the `./WEB-INF/classes` directory as shown in the instructions below._

[source,shell]
.Linux and macOS
----
cd /usr/local/cleanspeak/cleanspeak-webservice/web/WEB-INF/classes
jar xf ../lib/cleanspeak-filter-*.jar domains.properties

cd /usr/local/cleanspeak/cleanspeak-management-interface/web/WEB-INF/classes
jar xf ../lib/cleanspeak-filter-*.jar domains.properties
----

[source,shell]
.Windows
----
cd C:\cleanspeak\cleanspeak-webservice\web\WEB-INF\classes
jar xf ..\lib\cleanspeak-filter-*.jar domains.properties

cd C:\cleanspeak\cleanspeak-management-interface\web\WEB-INF\classes
jar xf ..\lib\cleanspeak-filter-*.jar domains.properties
----

Now that the `domains.properties` file has been extracted in both the management interface and the webservice, edit the file(s) and add additional TLDs that you wish to filter to the configuration. CleanSpeak will need to be restarted after you have performed these steps. If you need additional assistance please contact support be sending an email to support@inversoft.com.

*Stock Configuration*

Below is the configuration file shipped with CleanSpeak. This is shown for an example, this may not reflect the most recent version included in CleanSpeak.

[source,properties]
----
include::docs/3.x/tech/src/properties/domains.properties[]
----